INCLUDE "shmem.fh"

INTEGER PSYNC(SHMEM_BCAST_SYNC_SIZE)
PARAMETER (NLONG = 1)
INTEGER DEST, SOURCE
INTEGER SHMEM_N_PES
COMMON /COM/ DEST, SOURCE

DATA PSYNC /SHMEM_BCAST_SYNC_SIZE*SHMEM_SYNC_VALUE/

CALL SHMEM_INIT()
CALL SHMEM_BROADCAST64(DEST, SOURCE, NLONG, 0, 0, 0, SHMEM_N_PES(), PSYNC)
CALL SHMEM_FINALIZE()

END PROGRAM
